version: '2.1'
services:
  app:
    container_name: django-challenge-app
    build:
        context: .
        dockerfile: ./build/app/Dockerfile
    command: [sh, -c, "python3 manage.py runserver 0.0.0.0:8000"]
#    command: [sh, -c, "tail -f /dev/null"]
    environment:
      - DJANGO_SETTINGS_MODULE=django_challenge.settings
    ports:
      - '881:8000'
    volumes:
      - .:/code
    links:
      - database
      - redis

  database:
    container_name: django-challenge-database
    build:
        context: .
        dockerfile: ./build/db/Dockerfile
    environment:
      POSTGRES_USER: django-challenge
      POSTGRES_PASSWORD: django-challenge
      POSTGRES_DB: django-challenge
    ports:
      - '882:5432'
    volumes:
      - database-data:/var/lib/postgresql/data

  redis:
    container_name: django-challenge-redis
    image: redis:5.0-alpine3.8

  pgadmin:
    container_name: django-challenge-pgadmin
    build:
      context: .
      dockerfile: ./build/pgadmin/Dockerfile
    environment:
      PGADMIN_DEFAULT_EMAIL: and.dan19@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
    ports:
    - '883:80'
    depends_on:
    - database

volumes:
  database-data:

